import { Inter } from "next/font/google";
import Head from 'next/head';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Taapse pannu",
  description: "Generated by create next app",
  image: "https://res.cloudinary.com/dzhl8bgd9/image/upload/v1705656033/rpw8cgny9xvuecv9tcho.png",
  openGraph: {
    type: "website",
    title: "Create Next App",
    description: "Generated by create next app",
    image: "https://res.cloudinary.com/dzhl8bgd9/image/upload/v1705656033/rpw8cgny9xvuecv9tcho.png",
    url: "https://nextjs.org",

    images: [
      {
        url: "https://res.cloudinary.com/dzhl8bgd9/image/upload/v1705656033/rpw8cgny9xvuecv9tcho.png",
        width: 1200,
        height: 630,
        alt: "Og Image Alt",
      },
    ],

    url: "https://nextjs.org",
    site_name: "Next.js",
  },
  metadataBase: "https://your-domain.com", // Set your domain here
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta property="og:url" content={metadata.openGraph.url} />
      </Head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
