import { Inter } from "next/font/google";
import Head from 'next/head';


import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  image: "https://res.cloudinary.com/dzhl8bgd9/image/upload/v1705949513/prfdawpa7qmthwtk3tcb.png",
  
  openGraph: {
    type: "website",
    title: "Create Next App",
    description: "Generated by create next app",

    images: [
      {
        url: "https://res.cloudinary.com/dzhl8bgd9/image/upload/v1705949513/prfdawpa7qmthwtk3tcb.png",
        width: 1200,
        height: 630,
        alt: "Og Image Alt",
      },
    ],

    url: "https://nextjs.org",
    site_name: "Next.js",
  },
  metadataBase: "https://your-domain.com", // Set your domain here
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta property="og:url" content={metadata.openGraph.url} />
        <meta property="og:type" content={metadata.openGraph.type} />
        <meta property="og:title" content={metadata.openGraph.title} />
        <meta property="og:description" content={metadata.openGraph.description} />
        <meta property="og:image" content={metadata.openGraph.images[0].url} />
        <meta property="og:image:alt" content={metadata.openGraph.images[0].alt} />
        <meta property="og:site_name" content={metadata.openGraph.site_name} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@nextjs" />
        <meta name="twitter:title" content={metadata.openGraph.title} />
        <meta name="twitter:description" content={metadata.openGraph.description} />
        <meta name="twitter:image" content={metadata.openGraph.images[0].url} />
        <link rel="icon" href="https://res.cloudinary.com/dzhl8bgd9/image/upload/v1705949513/prfdawpa7qmthwtk3tcb.png" />
        <meta name="description" content={metadata.description} />
        <meta property="og:image" content={metadata.image} />
       
        <meta property="og:locale" content="en" />

      </Head>
      <html lang="en">
        <body className={inter.className}>
          {children}
        
        </body>
      </html>
    </>
  );
}
